USE api_vonakombi;

#CRIANDO A TABELA EXPORTACOES
(
CREATE TABLE EXPORTACOES 
	CO_ANO INT,
	CO_MES INT,
	CO_NCM VARCHAR(20),
	CO_UNID INT,
	CO_PAIS INT,
	SG_UF_NCM CHAR(2),
	CO_VIA INT,
	CO_URF INT,
	QT_ESTAT DECIMAL(15,2),
	KG_LIQUIDO DECIMAL(15,2),
	VL_FOB DECIMAL(15,2)
    );

#IMPORTAÇÃO E CONCATENACAO (2022, 2023 E 2024) NA TABELA EXPORTACOES
(
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/EXP_2024.csv'
INTO TABLE EXPORTACOES
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS;

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/EXP_2023.csv'
INTO TABLE EXPORTACOES
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS;

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/EXP_2022.csv'
INTO TABLE EXPORTACOES
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS;
)

#FILTRO - TABELA EXPORTACOES INCLUINDO VALORES AGREGADOS E EXCLUINDO VALORES AGREGADOS DIFERENTES DE 0
(
CREATE TABLE Exportacoes_VA AS
SELECT exportacoes.,
       (VL_FOB / NULLIF(KG_LIQUIDO, 0)) AS VALOR_AGREGADO
FROM exportacoes
WHERE (VL_FOB / NULLIF(KG_LIQUIDO, 0)) IS NOT NULL
  AND (VL_FOB / NULLIF(KG_LIQUIDO, 0)) != 0;
    )
 
#FILTRO - TABELA EXPORTACOES EXCLUINDOS VALORES ZERADOS E PAIS CONSIDERADOS PARAISOS FISCAIS
(
CREATE TABLE EXP_TRATADOS AS
SELECT
    EXPORTACOES.*,
    PAIS.NO_PAIS
FROM 
    EXPORTACOES
INNER JOIN
    PAIS
    ON EXPORTACOES.CO_PAIS = PAIS.CO_PAIS
WHERE
    EXPORTACOES.KG_LIQUIDO != 0
    AND EXPORTACOES.VL_FOB != 0;
)

CREATE TABLE Exportacoes_Final AS
SELECT exp_tratado.*, URF.NO_URF, (VL_FOB / KG_LIQUIDO) AS Valor_Agregado
FROM Exp_tratado
JOIN URF ON exp_tratado.CO_URF = urf.CO_URF
WHERE CO_NCM NOT IN ('27160000', '26011100')
AND VL_FOB < 100000000;


select count(*) from exportacoes_final;

SELECT * 
FROM EXPORTACOES_FINAL

WHERE NO_PAIS LIKE VL_FOB < 100000000;

SELECT *
FROM EXP_TRATADO
JOIN NCM ON EXP_TRATADO.CO_NCM = NCM.CO_NCM
WHERE NO_PAIS LIKE '%TURQUIA%'
  AND CO_MES = 8
  AND CO_ANO = 2022;
  
SELECT * FROM URF
WHERE URF.NO_URF LIKE '%BARCARENA%';

210151,217602,217802




drop table exportacoes_final;